spring:
  application:
    name: smart-family-budget-tracker
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/smart-family-budget-tracker-db
    username: smart_family_budget_tracker_admin
    password: Sagnik@219
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080


